services:
  database:
    image: postgres:15-alpine
    container_name: leaders_db
    restart: always
    environment:
      # Ces variables créent la base et l'utilisateur au premier lancement
      POSTGRES_DB: leaders_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      # Ce volume permet de ne pas perdre tes données si tu supprimes le conteneur
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
