
export const CHARACTER_IMAGES: Record<string, string> = {
    LEADER_RED: "/image/leaders/leader_red.png",
    LEADER_BLUE: "/image/leaders/leader_blue.png",
    ARCHER: "/image/archere.png",
    BRAWLER: "/image/cogneur.png",
    PROWLER: "/image/rodeuse.png",
    CAVALRY: "/image/cavalier.png",
    ACROBAT: "/image/acrobate.png",
    ILLUSIONIST: "/image/illusioniste.png",
    GRAPPLER: "/image/lance-grappin.png",
    MANIPULATOR: "/image/manipulatrice.png",
    INNKEEPER: "/image/tavernier.png",
    JAILER: "/image/geolier.png",
    PROTECTOR: "/image/protecteur.png",
    ASSASSIN: "/image/assassin.png",
    ROYAL_GUARD: "/image/garderoyal.png",
    VIZIER: "/image/vizir.png",
    NEMESIS: "/image/nemesis.png",
    OLD_BEAR: "/image/vieilours_ourson.png",
    CUB: "/image/vieilours_ourson.png",
};

export const CHARACTER_NAMES: Record<string, string> = {
    LEADER: "Leader",
    ACROBAT: "Acrobate",
    CAVALRY: "Cavalier",
    ILLUSIONIST: "Illusionniste",
    MANIPULATOR: "Manipulatrice",
    JAILER: "Geôlier",
    PROTECTOR: "Protecteur",
    BRAWLER: "Cogneur",
    GRAPPLER: "Lance-Grappin",
    NEMESIS: "Némésis",
    PROWLER: "Rôdeuse",
    INNKEEPER: "Tavernier",
    ARCHER: "Archère",
    ASSASSIN: "Assassin",
    ROYAL_GUARD: "Garde Royal",
    VIZIER: "Vizir",
    OLD_BEAR: "Vieil Ours",
    CUB: "Ourson",
};

export const CHARACTER_DATA: Record<string, { name: string; description: string; type: "ACTIVE" | "PASSIVE" | "SPECIAL" }> = {
    ACROBAT: { name: "Acrobate", description: "Saute en ligne droite par-dessus un Personnage adjacent. Peut effectuer jusqu'à deux sauts consécutifs.", type: "ACTIVE" },
    GRAPPLER: { name: "Lance-Grappin", description: "Se déplace jusqu’à un Personnage visible en ligne droite ou l’attire jusqu'à lui.", type: "ACTIVE" },
    CAVALRY: { name: "Cavalier", description: "Se déplace de deux cases en ligne droite.", type: "ACTIVE" },
    BRAWLER: { name: "Cogneur", description: "Se déplace sur la case d’un ennemi adjacent et le pousse sur l’une des trois cases opposées de votre choix.", type: "ACTIVE" },
    MANIPULATOR: { name: "Manipulatrice", description: "Déplace d’une case un ennemi visible en ligne droite et non-adjacent.", type: "ACTIVE" },
    ROYAL_GUARD: { name: "Garde Royal", description: "Se déplace, depuis n’importe quelle case, sur une case adjacente à votre Leader, puis peut ensuite se déplacer d'une case.", type: "ACTIVE" },
    PROWLER: { name: "Rôdeuse", description: "Se déplace sur n’importe quelle case non-adjacente à un ennemi.", type: "ACTIVE" },
    ILLUSIONIST: { name: "Illusionniste", description: "Échange de position avec un Personnage visible en ligne droite et non-adjacent.", type: "ACTIVE" },
    INNKEEPER: { name: "Tavernier", description: "Déplace d'une case un allié adjacent.", type: "ACTIVE" },
    ARCHER: { name: "Archère", description: "Participe à la capture du Leader adverse à une distance de deux cases en ligne droite. Ne participe pas s’il lui est adjacent.", type: "PASSIVE" },
    JAILER: { name: "Geôlier", description: "Les ennemis adjacents ayant une compétence active ne peuvent pas l’utiliser. N’interrompt pas une action en cours.", type: "PASSIVE" },
    ASSASSIN: { name: "Assassin", description: "Capture le Leader adverse, même sans autre allié participant à la capture.", type: "PASSIVE" },
    PROTECTOR: { name: "Protecteur", description: "Les compétences des ennemis ne peuvent déplacer ni le protecteur, ni ses alliés adjacents.", type: "PASSIVE" },
    VIZIER: { name: "Vizir", description: "Votre Leader peut se déplacer d’une case supplémentaire lors de son action.", type: "PASSIVE" },
    OLD_BEAR: { name: "Vieil Ours", description: "Recruté avec l'Ourson (2 pièces, comptent pour 1). L'Ourson ne capture pas le Leader. Déplacez l'un ou les deux à votre tour.", type: "SPECIAL" },
    NEMESIS: { name: "Némésis", description: "Ne joue pas à son tour. DOIT se déplacer de 2 cases (si possible) à la fin de toute action déplaçant le Leader adverse.", type: "SPECIAL" },
    LEADER: { name: "Leader", description: "Votre champion. S'il est capturé ou encerclé, la partie est perdue.", type: "SPECIAL" },
    CUB: { name: "Ourson", description: "Vient avec le Vieil Ours. Ne participe pas à la capture du Leader.", type: "SPECIAL" },
};
